spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-jpa-shop?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create #자동으로 테이블 생성
      properties:
        hibernate:
#          show_sql: true # System.in.out 에서 출력
          format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # 하이버네이트가 생성하는 SQL이 다보인다.